name: TeamPlugin
version: '2.0.8-20250321'
main: tcc.youajing.teamplugin.TeamPlugin
api-version: '1.20'
load: POSTWORLD
authors: [ YouaJing ]
folia-supported: true
soft-depend: [PlaceholderAPI]
commands:
  team:
    description: Manage your team.
    usage: /team ...
    default: true